platform :ios, ‘9.0’

target :’ELENews’ do
	pod 'MJRefresh'
	pod 'YYModel', '~> 1.0.4'
	pod 'Texture/PINRemoteImage', '~> 2.5.1'
	pod 'FDFullscreenPopGesture','1.1'
	pod 'Masonry', '~> 1.1.0'
	pod 'ReactiveCocoa','2.5'
	pod 'AFNetworking', '~> 3.1.0'
	pod 'PINRemoteImage/WebP'
	pod 'YYWebImage', '~> 1.0.5'
end
